sonar.projectKey=SelectIlLaFront
sonar.projectName=SelectIlLaFront
sonar.login=squ_300d1ccb14cbfd28af74e1ff4c3125adcd898223
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=js
sonar.eslint.eslintconfigpath= SelectIlLa_Backend/.eslintrc
sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.test.inclusions=**/*.spec.js